### ISSUE TITLE
1.3.6 unable to add new servers.

### ISSUE THREAD

**Issue by NotReallyACat** [theripper93/fvtt-player-client#11]
Just installed both windows and portable versions on two seperate devices when adding a new game nothing happens.

**Comment by NotReallyACat** [comment]
![image](https://github.com/theripper93/fvtt-player-client/assets/49882452/75cd22bd-5d74-4750-bfd1-268ebee78e5b)

**Comment by NotReallyACat** [comment]
> ![image](https://user-images.githubusercontent.com/49882452/266682788-75cd22bd-5d74-4750-bfd1-268ebee78e5b.png)

Same error across both versions on both devices.

**Comment by NotReallyACat** [comment]
@OmegaRogue, @theripper93 are either of you able to recreate this issue? I haven't tried it on linux only windows devices.

**Comment by OmegaRogue** [comment]
I can recreate it on a windows vm that hasnt had the client installed before, the problem is that the config.json file doesn't get copied to the build output anymore apparently since i did the move to vite/typescript, im looking for a fix

**Comment by theripper93** [comment]
@OmegaRogue can you send this fix as a PR
