### ISSUE TITLE
Module DDDice doesn`t work in the browser

### ISSUE THREAD

**Issue by igorteuri** [theripper93/fvtt-player-client#18]
Hi there. Amazing work with the browser. 

I just found an issue using DDDice Mode (https://github.com/dddice/dddice-foundry-plugin/issues/5). I have tried with chrome and other browsers, and the issue only appears in VTT Desktop Client. Here`s the errors whenever I try to roll any dice. 

Here`s the error I see in foundry UI
![image](https://github.com/dddice/dddice-foundry-plugin/assets/64547748/c64bb51d-bb24-43f3-8b55-ac765e665824)

Here's the error in console
![image](https://github.com/dddice/dddice-foundry-plugin/assets/64547748/2cf979b9-124b-4a35-894c-e22486c3fca9)

![image](https://github.com/dddice/dddice-foundry-plugin/assets/64547748/a4bad4d7-c22b-46f8-9554-a08378e631c3)

![image](https://github.com/dddice/dddice-foundry-plugin/assets/64547748/937db5c6-d67f-41fb-854e-77584799d026)

**Comment by theripper93** [comment]
Fixed in https://github.com/dddice/dddice-foundry-plugin/issues/5
