### ISSUE TITLE
[Idea] Display next session dates / descriptions

### ISSUE THREAD

**Issue by Gensokian** [theripper93/fvtt-player-client#24]
This might slow the initial "landing" page down, if not done in an async fassion, but if done correctly would be awesome to give an overview of future games.
If game pages are cached, the backgroudns could also be used, kinda like the little overview of all worlds in the foundry launcher.

![image](https://github.com/theripper93/fvtt-player-client/assets/9213561/df290f4e-d98a-478a-9463-6f144e440860)

**Comment by theripper93** [comment]
moved to https://github.com/OmegaRogue/fvtt-player-client, project mantained by new user
