### ISSUE TITLE
[Bug] Authentication Required (401) when server password is set

### ISSUE THREAD

**Issue by ZeroXNoxus** [theripper93/fvtt-player-client#26]
When the server is configured to request a username and password on first session login (following picture depicts the pop-up), the app simply returns "401 Authorization Required" as no username and password can be provided via the client. Would it be possible to add fields for the different games where you can enter such credentials?
![image](https://github.com/theripper93/fvtt-player-client/assets/29397572/a3ccbf1d-361d-4c58-8d48-74032e7d2cd5)

**Comment by theripper93** [comment]
moved to https://github.com/OmegaRogue/fvtt-player-client, project mantained by new user
