### ISSUE TITLE
Random freeze on world load

### ISSUE THREAD

**Issue by Talanor** [theripper93/fvtt-player-client#27]
Hello,

the client is freezing on foundy (re)load after logging in a game kind of randomly.

![image](https://github.com/theripper93/fvtt-player-client/assets/2121473/dea4e324-972a-4817-bef7-781a91c4355e)

It's not that common so the opportunity to test without modules hasn't come by yet.
To pinpoint a bit more, chromium has had the same issue while Chrome is consistent.

I'm on EndeavourOs, foundry v11.315, DnD5e 3.1.2.

**Comment by theripper93** [comment]
moved to https://github.com/OmegaRogue/fvtt-player-client, project mantained by new user
