### ISSUE TITLE
FVTT Player Client suddenly in dark mode with invisible UI

### ISSUE THREAD

**Issue by dmpunks** [theripper93/fvtt-player-client#29]
I've been using the vtt client for the past few days but when I started it up, everything is dark except for the Add Game button and the field names for the game name and url? I can still click on the game I added if I hover my mouse over where it is. The 3 menu icons on the upper right seem to be invisible as well. I can click on them but can't read what pops up...
![image](https://github.com/theripper93/fvtt-player-client/assets/1963509/8e927d40-e075-4c1b-8623-a8e6a4fe2621)

**Comment by VitamiinaC** [comment]
I'm having the same problem, reinstalling the version and switching to the portable version didn't solve it either.
Did you find anything?

**Comment by Zarkoncheg** [comment]
Same problem

**Comment by theripper93** [comment]
moved to https://github.com/OmegaRogue/fvtt-player-client, project mantained by new user
