### ISSUE TITLE
web-bluetooth connection dialog broken

### ISSUE THREAD

**Issue by alterNERDtive** [theripper93/fvtt-player-client#31]
I’ve been thinking about getting some Bluetooth dice, so I’ve been playing around with the [Pixels dice integration](https://foundryvtt.com/packages/pixels).

I managed to enable web-bluetooth by passing ` --enable-experimental-web-platform-features --enable-web-bluetooth` to the executable. But when this dialog (pic taken off Chromium)

![image](https://github.com/theripper93/fvtt-player-client/assets/53827887/7e8a5c5a-39cc-4cd1-a203-ca8c26adb31d)

should appear after hitting “Add Pixel Dice” in the settings, instead I immediately get

![image](https://github.com/theripper93/fvtt-player-client/assets/53827887/fe7e82d9-6751-4470-813f-85e7fa9fd53f)

which, as it states, appears in Chromium when I actually cancel the thing. It appears that the Electron app either blocks the dialog from opening or somehow causes it to die instantly.

**Comment by theripper93** [comment]
moved to https://github.com/OmegaRogue/fvtt-player-client, project mantained by new user
