### ISSUE TITLE
Does not open on macOS: "vtt-desktop-client" is damaged.

### ISSUE THREAD

**Issue by johncarney** [theripper93/fvtt-player-client#33]
When I try to open the macOS arm64 version of vtt-desktop-client on my MacBook, it says the file is damaged. This is on an M2 Max MBP.

<img width="252" alt="image" src="https://github.com/user-attachments/assets/6772b31f-92de-45d4-908c-212d572c76ea">

**Comment by johncarney** [comment]
For the record, the macOS x64 version of 1.5.4 works just fine, though I'm running on an M2 MBP, so I'm guessing the emulation is likely to impact on performance.

**Comment by Kianfu** [comment]
Having the same problem with my 15" M2 Macbook Air.

**Comment by Tarubain** [comment]
Same problem with OSX 14.6.1 on MBP M1

**Comment by theripper93** [comment]
moved to https://github.com/OmegaRogue/fvtt-player-client, project mantained by new user
