### ISSUE TITLE
VTT Client (Portable) Using APPDATA

### ISSUE THREAD

**Issue by gkanks** [theripper93/fvtt-player-client#34]
I'm using what I think is the latest edition (1.5.5) of the portable version and it seems to ignore what is in .\resources\app\config.json and creates the whole C:\Users\myuser\AppData\Roaming\vtt-desktop-client folder structure and works out of there. I have tried deleting the structure and it just starts by making a fresh set every time and ignoring the local config file.

If I add any other server instance using the add button, close it and reopen it the config items from the local config get pulled into as well as the item I added.

After doing that it seems to use data both from 
.\resources\app\config.json
and 
C:\Users\myuser\AppData\Roaming\vtt-desktop-client\userData.json

![image](https://github.com/user-attachments/assets/00b437da-231d-4c8d-927d-423915cce5e2)
![image](https://github.com/user-attachments/assets/00b7839e-98d6-4c72-b44b-13a2fc202493)
![image](https://github.com/user-attachments/assets/c2a345fe-fb13-466c-845f-4b36be98518f)

**Comment by theripper93** [comment]
moved to https://github.com/OmegaRogue/fvtt-player-client, project mantained by new user
