### ISSUE TITLE
Error when saving password on Linux

### ISSUE THREAD

**Issue by OmegaRogue** [theripper93/fvtt-player-client#7]
Saving a password on Linux doesn't seem to work and leads to this error popup:
![image](https://github.com/theripper93/fvtt-player-client/assets/24958536/32395752-005c-4944-8782-7e8a46188b79)

**Comment by OmegaRogue** [comment]
I'm investigating this, this issue can be assigned to me, I created it to track the progress

**Comment by OmegaRogue** [comment]
This might be related to me not running a desktop environment and the automatic detection from electron for some reason not finding the gnome keyring daemon running

**Comment by OmegaRogue** [comment]
https://www.electronjs.org/docs/latest/api/safe-storage
This seems to occur when running an unrecognized desktop environment, to fix it, you need to run it with one of these command line flags, or build it with a line like
```js
app.commandLine.appendSwitch("password-store", "gnome")
```
included after the other similar statements in main.js

**Comment by OmegaRogue** [comment]
I'm not sure if this issue is even fixable then without adding custom logic to properly detect available password stores, the way electron does it isn't very good

**Comment by alterNERDtive** [comment]
I’m using sway, Gnome keyring is up and running. I run into the same error trying to save a _user password_, `--password-store="gnome-libsecret"` fixes that one while `--password-store="basic"` still errors out, FYI.

The reason I’m posting though is that I simply cannot store the _admin password_ in any way. No error message, but it neither uses nor stores the password. That is with either of the command line options.

**Comment by theripper93** [comment]
moved to https://github.com/OmegaRogue/fvtt-player-client, project mantained by new user
