### ISSUE TITLE
"Ctrl -" makes the UI smaller, but using "Ctrl +" does not make it bigger. Reset with Ctrl 0 works.

### ISSUE THREAD

**Issue by FaanB** [theripper93/fvtt-player-client#8]
I used the Ctrl - shortcut to zoom out, but I went too far and now the text is too small to read. (even tried at setup screen to be sure it isn't a module using it as a shortcut for something else) 

Using "Ctrl 0" to reset it to normal does work, so it is fixable.

I didn't see anything written about it in the project descriptions, so I mainly want to post this as a 'just incase' someone else has an issue like this. (and maybe it is a bug that Ctrl + doesn't work?)

**Comment by theripper93** [comment]
https://wiki.theripper93.com/free/vtt-desktop-client#keyboard-shortcuts
