### ISSUE TITLE
[Feature Request] Navigation Buttons?

### ISSUE THREAD

**Issue by Grandsome** [theripper93/fvtt-player-client#9]
Given that this is supposed to be client for players, a minimal navigation UI would be very helpful to reload the page and go back to login portal and whatnot.

Thanks for the project, it's gonna be a lifesaver for players with "wild browsers".

**Comment by OmegaRogue** [comment]
I'll look into it!

**Comment by OmegaRogue** [comment]
What buttons would you expect to be in such a navigation UI?

**Comment by theripper93** [comment]
This is meant to mirror the foundry client experience, the lack of buttons is intentional. To go back to login you can just logout from inside foundry, and you can just ctrl+r to refresh. I like the design as is without buttons this is not a feature I’m willing to add/approve

**Comment by OmegaRogue** [comment]
The Problem is that you can't go back to the server selection screen after connecting once

**Comment by theripper93** [comment]
I'm aware of that, but I don't want a navigation bar taking up the screen when restarting the client takes 1 second

**Comment by OmegaRogue** [comment]
There's already some js being injected by the client, it should be possible to inject some more and add that button into the normal foundry UI i think

**Comment by theripper93** [comment]
Yes, but I inject only in the login screen, I don't want to inject in the in game interface

**Comment by OmegaRogue** [comment]
In that case I will maintain a fork with that functionality: https://github.com/OmegaRogue/fvtt-player-client/tree/fork

**Comment by OmegaRogue** [comment]
https://github.com/OmegaRogue/fvtt-player-client/releases
This should work

**Comment by Grandsome** [comment]
A "back" and "forward", and "reload" button, there must also maybe be a way to get the navigation bar to auto-hide. Sorry for late comment. i'll have a look at current releaseé

**Comment by OmegaRogue** [comment]
> A "back" and "forward", and "reload" button, there must also maybe be a way to get the navigation bar to auto-hide. Sorry for late comment. i'll have a look at current releaseé

What would the purpose of forward and back buttons be? I can somewhat see the use of a reload button, tho you can just press F5 for that
